version: "3"
services:
 
  employee-api:
    image: localhost:5000/employee-api
    env_file:
      - .env.prod
    ports:
      - "3333:3333"
    depends_on:
      - auth-api
    networks:
      - employee
 
  auth-api:
    image: localhost:5000/auth-api
    env_file:
      - .env
    ports:
      - "33334:3334"
    networks:
      - employee

networks:
  employee:
    driver: bridge