name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Employee API
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chan4lk/employee-api:latest
          file: apps/employee-management/dockerfile
      -
        name: Build and push Auth API
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chan4lk/auth-api:latest
          file: apps/auth-api/dockerfile