name: Automated Performance tests using K6

on: 
    workflow_dispatch:
  
# Environment variables available to all jobs and steps in this workflow
env:
  Configuration: "Debug"
  API_HOST: "20.237.23.60"
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Get Data k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/k6/test.js
          cloud: true
          token: ${{ secrets.K6_TOKEN }}

      - name: Run SignUp k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: tests/k6/test-create.js
          cloud: true
          token: ${{ secrets.K6_TOKEN }}