name: Automated API tests using Postman CLI

on:
    workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  
# Environment variables available to all jobs and steps in this workflow
env:
  API_HOST: "${{ secrets.HOST }}"
  APISERVER: "${{ secrets.KUBERNETES_API_SERVER_URL}}"
  access_token: "${{ secrets.KUBERNETES_API_SERVER_TOKEN}}"

jobs:
  automated-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run API tests
        run: |
          cd ./tests/postman
          postman collection run "./api.postman_collection.json" --insecure -e "./api.postman_environment.json" --env-var baseUrl="http://${{ env.API_HOST }}" --env-var APISERVER="${{ env.APISERVER }}" --env-var access_token="${{ env.access_token }}"
