name: Automated API tests using Postman CLI

on: push

jobs:
  automated-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run API tests
        run: |
          cd ./tests/postman
          postman collection run "./api.postman_collection.json" -e "./api.postman_environment.json"

  automated-specflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          cd tests/specflow/MicroServices.Testing
          dotnet restore

      - name: Build
        run: |
          cd tests/specflow/MicroServices.Testing
          dotnet build --configuration Release --no-restore
          
      - uses: cryptic-wizard/run-specflow-tests@v1.3.1
        with:
          test-assembly-path: tests/specflow/MicroServices.Testing/bin/Release/net6.0
          test-assembly-dll: MicroServices.Testing.dll
          output-html: MicroServices.Testing.html