name: Automated API tests using Postman CLI

on: push

jobs:
  automated-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run API tests
        run: |
          cd ./tests/postman
          postman collection run "./api.postman_collection.json" -e "./api.postman_environment.json"

  automated-specflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          cd tests/specflow/MicroServices.Testing
          dotnet restore

      - name: Build
        run: |
          cd tests/specflow/MicroServices.Testing
          dotnet build --configuration Debug --no-restore
       
      - uses:  cryptic-wizard/run-specflow-tests@v1.3.1
        with:
          test-assembly-dll: tests/specflow/MicroServices.Testing/bin/Debug/net6.0/MicroServices.Testing.dll
          test-execution-json: tests/specflow/MicroServices.Testing/bin/Debug/net6.0/TestExecution.json
          output-html: MicroServices.Testing.html
          framework: net6.0
          configuration: 'Debug'
          no-build: true
          logger: trx
          logger-file-name: ../../MicroServicesResults.trx
          upload-artifact: true

      - name: Publish Specflow Test Logs
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: SpecflowLogs
          path: |
            MicroServicesResults.trx