name: Automated API tests using Postman CLI

on: push

permissions:
  checks: write
  pull-requests: write
  
# Environment variables available to all jobs and steps in this workflow
env:
  TEST_DLL: "tests/specflow/MicroServices.Testing/bin/Debug/net6.0/MicroServices.Testing.dll"
  TEST_JSON: "tests/specflow/MicroServices.Testing/bin/Debug/net6.0/TestExecution.json"
  TEST_OUTPUT: "MicroServices.Testing.html"
  Configuration: "Debug"

jobs:
  automated-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run API tests
        run: |
          cd ./tests/postman
          postman collection run "./api.postman_collection.json" -e "./api.postman_environment.json"
